# I used AI to help define some terminology in order to enhance my quiz app to work better. 
# This helped me better understand how these work and why it makes it so much more efficient compared to other older and longer methods. 
# Ex: Lines 24, FileNotFoundError, json.JSONDecodeError; Other lines down the code: enumerate, ValueError, IndexError, etc.
import json
import random
import os

# Get quiz questions from file, or bails if it is not there or missing
def grab_questions(topic):
    file_name = f"{topic}_questions.json"
    
    if not os.path.isfile(file_name):
        print(f"R.I.P.'{file_name}' is missing!")
        exit(1)
    
    with open(file_name, "r") as f:
        return json.load(f)

# Save scores and tracks your progress!
def record_score(player, points, topic):
    score_file = "scores.json"
    try:
        with open(score_file, "r") as f:
            scores = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        scores = {}

    if player not in scores:
        scores[player] = {}
    if topic not in scores[player]:
        scores[player][topic] = []
    
    scores[player][topic].append(points)

    with open(score_file, "w") as f:
        json.dump(scores, f, indent=4)

# Making sure that what the users put in for their answer is valid
def grab_answers(num_options):
    choices = [str(i) for i in range(1, num_options + 1)]
    
    while True:
        picking_choices = input("Pick your answer(s), space-separated: ").split()
        valid = [ans for ans in picking_choices if ans in choices]
        
        if valid:
            return valid
        
        print(f"Please pick the right options! Pick something from 1-{num_options}.")

# Displaying the actual quiz questions and checking for correctness!
def show_questions(question, choices, correct_answers):
    print(f"\n {question} ")
    # Lines 56-60 were generated by ChatGPT with the prompt to:
    # Generate a loop to display multiple-choice options with numbering and allow users to select an answer
    # I wanted to make sure this logic was reviewed as well as modified to ensure that it aligns with the course requirement 
    for i, choice in enumerate(choices, 1):
        print(f" {i}. {choice}")

    user_answers = grab_answers(len(choices))
    picked = [choices[int(ans) - 1] for ans in user_answers]

    if sorted(picked) == sorted(correct_answers):
        print("Lets go! Nice job!")
        return True
    else:
        print(f"Nahhhh! Here is the right answer(s): {', '.join(correct_answers)}")
        return False

# Over here is the main quiz function. Topic selection, tracking scores, and helps run the quiz.
def quiz_time():
    player = input("Enter your username here! Or just put something Idk! ")
    categories = ["anime", "video_games"]
# lines 72-91 were mostly generated with GPTs assistance with the prompt: 
# Create a user friendly interface to select a quiz topic, handle invalid inputs, shuffle questions, and tracking scores
# I modified parts of the logic, adjusted the format for better readability, as well as having customized error messages. 
    print("\nPick a topic from two choices:")
    for i, cat in enumerate(categories, 1):
        print(f" {i}. {cat.replace('_', ' ').title()}")

    try:
        topic = categories[int(input("> ")) - 1]
    except (ValueError, IndexError):
        print("That ain't a choice bruh! Guess you gonna have to go with 'anime'!")
        topic = "anime"

    questions = grab_questions(topic)
    random.shuffle(questions)

    score = 0
    for q in questions:
        if show_questions(q["question"], q["options"], q["correct_answers"]):
            score += 1

    print(f"\n {player}, your score report isss {score}/{len(questions)}! GGs! ")
    record_score(player, score, topic)

# Starts the quiz
quiz_time()
