import json
import random
import os

# Get quiz questions from file, or bails if it is not there or missing
def grab_questions(topic):
    file_name = f"{topic}_questions.json"
    
    if not os.path.isfile(file_name):
        print(f"R.I.P.'{file_name}' is missing!")
        exit(1)
    
    with open(file_name, "r") as f:
        return json.load(f)

# Save scores and tracks your progress!
def record_score(player, points, topic):
    score_file = "scores.json"
    try:
        with open(score_file, "r") as f:
            scores = json.load(f)
            # I use AI here to look these terms up
    except (FileNotFoundError, json.JSONDecodeError):
        scores = {}

    if player not in scores:
        scores[player] = {}
    if topic not in scores[player]:
        scores[player][topic] = []
    
    scores[player][topic].append(points)

    with open(score_file, "w") as f:
        json.dump(scores, f, indent=4)

# Making sure that what the users put in for their answer is valid
def grab_answers(num_options):
    choices = [str(i) for i in range(1, num_options + 1)]
    
    while True:
        picking_choices = input("Pick your answer(s), space-separated: ").split()
        valid = [ans for ans in picking_choices if ans in choices]
        
        if valid:
            return valid
        
        print(f"Please pick the right options! Pick something from 1-{num_options}.")

# Displaying the actual quiz questions and checking for correctness!
def show_questions(question, choices, correct_answers):
    print(f"\n {question} ")
    # Lines 57-60 were generated by ChatGPT with the prompt to:
    # Generate a loop to display multiple-choice options with numbering and allow users to select an answer
    # I wanted to make sure this logic was reviewed as well as modified to ensure that it aligns with the course requirement 
    i = 1
    for option in choices:
        print(f"{i}. {option}")
        i += 1
        
    user_answers = grab_answers(len(choices))
    picked = [choices[int(ans) - 1] for ans in user_answers]

    if sorted(picked) == sorted(correct_answers):
        print("Lets go! Nice freakin job!")
        return True
    else:
        print(f"Nah that ain't it! Here is the right answer(s): {', '.join(correct_answers)}")
        return False

# Over here is the main quiz function. Topic selection, tracking scores, and helps run the quiz.
def quiz():
    # lines 77-95 were mostly generated with GPTs assistance with the prompt: 
    # Create a user friendly interface to select a quiz topic, handle invalid inputs, shuffle questions, and tracking scores
    # I modified parts of the logic, adjusted the format for better readability, as well as having customized error messages. 
    username = input("Enter your username here! Or just put something Idk! ")
    topics = ["anime", "video_games"]
    print("Pick a topic from two choices: ")
    i = 1
    for topic in topics:
        print(f"{i}. {topic.replace('_', ' ').title()}")
        i += 1
    selected_topic = topics[int(input("Enter the number of your chosen topic (1 or 2): ")) - 1]
    
    questions = grab_questions(selected_topic)
    random.shuffle(questions)
    
    score = 0
    for q in questions:
        if show_questions(q["question"], q["options"], q["correct_answers"]):
            score += 1
    
    print(f"\n{username}, your score report isss {score}/{len(questions)}! GGs!")
    record_score(username, score, selected_topic)

# Starts the quiz
quiz()
